-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--   sources = {
--     null_ls.builtins.formatting.standardjs,
--     null_ls.builtins.formatting.standardts,
--     null_ls.builtins.diagnostics.standardjs,
--     null_ls.builtins.formatting.sqlfluff.with({
--       extra_args = { "--dialect", "tsql" },
--     }),
--   },
-- })
